'use client';
import { useEffect, useRef, useState } from 'react';
import { Box, RotateCcw, Play, Pause, ArrowUpRight, SlidersHorizontal, Braces, Grid2X2, Move3D, Check, Info } from 'lucide-react';
import { IDENTITY, parseMatrix, scalar, determinant, rank, formatMatrix, type Matrix } from '../lib/matrix';
import Scene, { type SceneHandle } from './scene';
import { registerMatrixTool } from '../lib/webmcp';
const presets = [
 {name:'Shear',hint:'Tilt space',matrix:[[1,.7,0],[0,1,0],[0,0,1]]},
 {name:'Rotation',hint:'45° around z',matrix:[[Math.SQRT1_2,-Math.SQRT1_2,0],[Math.SQRT1_2,Math.SQRT1_2,0],[0,0,1]]},
 {name:'Scale',hint:'Stretch the axes',matrix:[[1.7,0,0],[0,.7,0],[0,0,1.3]]},
 {name:'Projection',hint:'Flatten onto xy',matrix:[[1,0,0],[0,1,0],[0,0,0]]},
];
const initial=presets[0].matrix;
export default function Home(){
 const [matrix,setMatrix]=useState<Matrix>(initial),[cells,setCells]=useState(initial.map(r=>r.map(String))),[source,setSource]=useState(formatMatrix(initial));
 const [editor,setEditor]=useState('grid'),[error,setError]=useState(''),[selected,setSelected]=useState('Shear');
 const [mode,setMode]=useState<'transform'|'vectors'>('transform'),[progress,setProgress]=useState(1),[playing,setPlaying]=useState(false);
 const [grid,setGrid]=useState(true),[original,setOriginal]=useState(true),[vectors,setVectors]=useState(true),[highlight,setHighlight]=useState<number|null>(null);
 const scene=useRef<SceneHandle>(null); const det=determinant(matrix);
 const apply=(m:Matrix,name='Custom')=>{setMatrix(m);setCells(m.map(r=>r.map(String)));setSource(formatMatrix(m));setError('');setSelected(name);setProgress(1);setPlaying(false);};
 useEffect(()=>registerMatrixTool(apply),[]);
 useEffect(()=>{if(!playing)return;let id:number;let last:number|null=null;let elapsed=progress;const tick=(time:number)=>{const delta=last===null?0:Math.min(time-last,50)/2600;last=time;elapsed=Math.min(1,elapsed+delta);setProgress(elapsed);if(elapsed===1){setPlaying(false);return;}id=requestAnimationFrame(tick);};id=requestAnimationFrame(tick);return()=>cancelAnimationFrame(id);},[playing]);
 const editCell=(r:number,c:number,value:string)=>{const next=cells.map(row=>[...row]);next[r][c]=value;setCells(next);setSelected('Custom');try{const m=next.map(row=>row.map(scalar));setMatrix(m);setSource(formatMatrix(m));setError('');}catch(e){setError((e as Error).message);}};
 const editText=(value:string)=>{setSource(value);setSelected('Custom');try{const m=parseMatrix(value);setMatrix(m);setCells(m.map(r=>r.map(String)));setError('');}catch(e){setError((e as Error).message);}};
 return <main className="workspace"><header className="topbar"><a className="brand" href="/" aria-label="Matrix Space home"><span className="brand-icon"><Box size={23}/></span>matrix<span className="brand-light">space</span><span className="beta">LAB</span></a><div className="top-caption">A little algebra. A new perspective.</div><span className="live"><i/> Interactive 3D</span></header>
 <div className="app-body"><aside className="sidebar"><div className="intro"><span className="eyebrow">LINEAR ALGEBRA PLAYGROUND</span><h1>Give numbers<br/>a new dimension<span>.</span></h1><p>Edit a matrix. See how it shapes space.</p></div>
 <section><div className="section-heading"><h2><span className="matrix-symbol">A</span> Transformation matrix</h2><span className="dimension">3 × 3</span></div><div className="editor-tabs"><button className={editor==='grid'?'active':''} onClick={()=>setEditor('grid')}><Grid2X2 size={15}/> Grid</button><button className={editor==='text'?'active':''} onClick={()=>setEditor('text')}><Braces size={15}/> Text input</button></div>
 {editor==='grid'?<div className="matrix-editor"><span className="matrix-equals">A =</span><div className="matrix-brackets"><div className="column-labels"><span>x</span><span>y</span><span>z</span></div><div className="matrix-cells">{cells.flatMap((row,r)=>row.map((value,c)=><input key={`${r}-${c}`} aria-label={`Row ${r+1}, column ${c+1}`} className={highlight===c?'highlighted':''} value={value} onFocus={()=>setHighlight(c)} onBlur={()=>setHighlight(null)} onChange={e=>editCell(r,c,e.target.value)} onKeyDown={e=>{if(e.key==='Enter'){e.preventDefault();e.currentTarget.closest('.matrix-cells')?.querySelectorAll('input')[(r*3+c+1)%9]?.focus();}}} onPaste={e=>{const text=e.clipboardData.getData('text');if(/[\t\n;\[\]]/.test(text)){e.preventDefault();try{apply(parseMatrix(text));}catch(err){setError((err as Error).message);}}}}/>))}</div></div></div>:<textarea className="text-editor" aria-label="Matrix text input" spellCheck={false} value={source} onChange={e=>editText(e.target.value)}/>}
 <div className={`input-status ${error?'error':''}`} role="status">{error?<><Info size={14}/>{error} Last valid matrix shown.</>:<><Check size={14}/>{editor==='grid'?'Live updates · fractions & sqrt(2) supported':'Rows: semicolons or newlines · paste arrays or cells'}</>}</div><button className="reset-matrix" onClick={()=>apply(IDENTITY,'Identity')}><RotateCcw size={14}/> Reset to identity</button></section>
 <section><div className="section-heading"><h2>Try a transformation</h2><ArrowUpRight size={16}/></div><div className="presets">{presets.map((p,i)=><button key={p.name} className={selected===p.name?'preset active':'preset'} onClick={()=>apply(p.matrix,p.name)}><span className="preset-glyph">{['▱','↻','⤢','⊥'][i]}</span><strong>{p.name}</strong><small>{p.hint}</small></button>)}</div></section>
 <section><div className="section-heading"><h2><SlidersHorizontal size={15}/> Scene layers</h2></div>{([['Reference grid',grid,setGrid],['Original shape',original,setOriginal],['Basis vectors',vectors,setVectors]] as const).map(([label,value,setter])=><label className="toggle-row" key={label}><span>{label}</span><input type="checkbox" checked={value} onChange={e=>setter(e.target.checked)}/><span className="switch"/></label>)}</section><div className="sidebar-foot"><span className="keycap">↵</span> next cell <span className="keycap">Tab</span> move through matrix</div></aside>
 <section className="viewport" aria-label="Interactive three dimensional matrix plot"><Scene ref={scene} matrix={matrix} progress={progress} grid={grid} original={original} vectors={vectors} mode={mode} highlight={highlight}/>
 <div className="scene-top"><div className="view-tabs"><button className={mode==='transform'?'active':''} onClick={()=>setMode('transform')}><Box size={16}/> Transformation</button><button className={mode==='vectors'?'active':''} onClick={()=>setMode('vectors')}><Move3D size={16}/> Vectors</button></div><button className="icon-button" title="Reset camera" aria-label="Reset camera" onClick={()=>scene.current?.view('perspective')}><RotateCcw size={17}/></button></div>
 <div className="scene-title"><span className="eyebrow">{mode==='transform'?'SPACE TRANSFORMED':'COLUMN VECTORS'}</span><h2>{selected}<span> / ℝ³</span></h2></div><div className="camera-controls"><span>VIEW</span>{['3D','XY','XZ','YZ'].map((v,i)=><button key={v} onClick={()=>scene.current?.view(['perspective','xy','xz','yz'][i])}>{v}</button>)}<button onClick={()=>scene.current?.view('fit')}>Fit</button></div>
 <div className="legend">{['x','y','z'].map((axis,i)=><button key={axis} onMouseEnter={()=>setHighlight(i)} onMouseLeave={()=>setHighlight(null)} onFocus={()=>setHighlight(i)} onBlur={()=>setHighlight(null)}><i className={`axis-${axis}`}/>{axis} basis</button>)}<span><i className="original-dot"/>original</span></div>
 <div className="bottom-panel"><div className="stats"><div><span>DETERMINANT</span><strong>{Number(det.toFixed(4))}<small>det(A)</small></strong></div><div><span>RANK</span><strong>{rank(matrix)}<small>/ 3 dimensions</small></strong></div><div><span>VOLUME SCALE</span><strong>{Number(Math.abs(det).toFixed(3))}×<small>{Math.abs(det)<1e-10?'Collapsed space':det<0?'Orientation reversed':'Orientation preserved'}</small></strong></div></div>
 <div className="timeline"><button className="play-button" aria-label={playing?'Pause transformation':'Play transformation'} onClick={()=>{if(progress>=1)setProgress(0);setPlaying(p=>!p);}}>{playing?<Pause size={18}/>:<Play size={18}/>}</button><div className="timeline-track"><div><strong>Animate transformation</strong><span>{Math.round(progress*100)}%</span></div><input aria-label="Transformation progress" type="range" min="0" max="1" step="0.001" value={progress} onChange={e=>{setPlaying(false);setProgress(Number(e.target.value));}}/><div className="timeline-labels"><span>Identity</span><span>Matrix A</span></div></div></div><div className="interpolation-note">Linear interpolation · A(t) = (1 − t)I + tA</div></div><div className="scene-help">Drag to orbit <b>·</b> Scroll to zoom <b>·</b> Right-drag to pan</div></section></div></main>;
}
